# Netlify Configuration für Trigger-Tagebuch App

[build]
  # Build Command
  command = "npm run build"

  # Output Directory nach Angular Build
  publish = "dist/trigger-tagebuch/browser"

  # Node Version
  node_version = "18"

[build.environment]
  # Angular CLI nutzt diese Variable
  NODE_VERSION = "18"

# SPA Routing - alle Routen zu index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Serverless Functions (für Claude API!)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Headers für Sicherheit
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Optimierungen
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
